GRANT USAGE ON SCHEMA auth TO "authenticated";
GRANT USAGE ON SCHEMA auth TO "anon";
GRANT USAGE ON SCHEMA auth TO "authenticator";
GRANT SELECT ON ALL TABLES IN SCHEMA auth TO "authenticator";
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA auth TO "authenticated";
ALTER DEFAULT PRIVILEGES IN SCHEMA auth GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO "authenticated";